# GitHub command-line tool
brew "gh"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# Cross-shell prompt for astronauts
brew "starship"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Agent orchestration platform
cask "antigravity"
# Terminal interface for Antigravity agents
cask "antigravity-cli"
# AI Coding Agent IDE
cask "antigravity-ide"
# Application uninstaller
cask "appcleaner"
# App to build and share containerised applications and microservices
cask "docker-desktop"
cask "font-sauce-code-pro-nerd-font"
# Web browser
cask "google-chrome"
# Team communication and collaboration software
cask "slack"
