# Homebrewの設定
eval "$(/opt/homebrew/bin/brew shellenv zsh)"
export HOMEBREW_BUNDLE_FILE="$HOME/.Brewfile"
export HOMEBREW_BUNDLE_DUMP_NO_VSCODE=true

# Starshipの設定
eval "$(starship init zsh)"

# miseの設定
eval "$(mise activate zsh)"

# パス追加
export PATH="$HOME/.antigravity-ide/antigravity-ide/bin:$PATH"
